# Generated by Django 6.0 on 2025-12-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
