# Generated by Django 6.0 on 2025-12-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
