# Generated by Django 6.0 on 2025-12-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_user_marks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
