# Generated by Django 6.0 on 2025-12-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marks',
        ),
    ]
